### ISSUE TITLE
Linux error

### ISSUE THREAD

**Issue by f0rtis** [outboundio/lib-php#3]
https://github.com/outboundio/lib-php/blob/cfe85846e17f77c147849c78286a8872bd9a3e61/composer.json#L23

Linux is case-sensitive and it can't find the file, as it was renamed from Outbound.php to outbound.php

**Comment by f0rtis** [comment]
I've created a PR to fix this issue
https://github.com/outboundio/lib-php/pull/4

**Comment by ryan-scott-dev** [comment]
I just released v2.2.1 which includes the changes in #4. 
https://packagist.org/packages/outbound/outbound-php#v2.2.1

Thanks for your contributions 😺
